# Generated by Django 6.0.4 on 2026-05-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_voterrecord_member_is_voter_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterrecord',
            name='polling_station',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='ward',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='voterrecord',
            name='id_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='voterrecord',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
