# Generated by Django 6.0.4 on 2026-05-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_voterrecord_polling_station_voterrecord_ward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterrecord',
            name='id_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='voterrecord',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
