# Generated by Django 6.0.4 on 2026-05-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_voterrecord_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterrecord',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
