# Generated by Django 6.0.4 on 2026-05-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_voterrecord_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='official_polling_station',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='official_ward',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
