# Generated by Django 6.0.4 on 2026-05-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_official_ward_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterrecord',
            name='date_of_birth',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
